postgresql:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    POSTGRES_DB: root
    POSTGRES_USER: root
    POSTGRES_PASSWORD: fer67na
    PGDATA: /var/lib/postgresql/data
    DB_HOST: 127.0.0.1
  volumes:
    - ./postgres-data:/var/lib/postgresql/data
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready" ]
    interval: 30s
    timeout: 60s
    retries: 10
    start_period: 120s
  restart: always
  networks:
    - dbnet